### ISSUE TITLE
Get-ChildItem: Cannot find path '/home/runner/work/maester-tests/maester-tests/tests/' because it does not exist.

### ISSUE THREAD

**Issue by fdicarlo** [maester365/maester#188]
After the last update I am getting the following error

```
WARNING: The version '5.5.0' of module 'Pester' is currently in use. Retry the operation after closing the applications.

Get-ChildItem: Cannot find path '/home/runner/work/maester-tests/maester-tests/tests/' because
it does not exist.
Error: System.Management.Automation.RuntimeException: No test files were found and no scriptblocks were provided. Please ensure that you provided at least one path to a *.Tests.ps1 file, or a directory that contains such file. Or that you provided a ScriptBlock test container.
Message
  at Invoke-Pester<End>, /usr/local/share/powershell/Modules/Pester/5.5.0/Pester.psm1: line 5042
  at Invoke-Maester, /home/runner/.local/share/powershell/Modules/Maester/0.0.128/public/Invoke-Maester.ps1: line 254
  at <ScriptBlock>, /home/runner/work/_temp/52d05bc6-33f9-4f[83](https://github.com/Cyber-Monks/maester-tests/actions/runs/9196716704/job/25295446060#step:6:84)-ab45-30f22f7e11ea.ps1: line 17
  at <ScriptBlock>, <No file>: line 1
Get-Content: /home/runner/work/_temp/52d05bc6-33f9-4f83-ab45-30f22f7e11ea.ps1:20
Line |
  20 |  $summary = Get-Content test-results/test-results.md
     |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/runner/work/maester-tests/maester-tests/test-results/test-results.md' because it does not exist.
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
```

it seems like is checking the wrong folder but this is my main.yml:

```
name: Maester Daily Tests

on:
  push:
    branches: ["main"]
  # Run once a day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%d-T%H%M%S')" >> $GITHUB_ENV
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
    - name: Run Maester
      uses: azure/powershell@v2
      with:
        inlineScript: |
          # Get Token
          $token = az account get-access-token --resource-type ms-graph
          # Connect to Microsoft Graph
          $accessToken = ($token | ConvertFrom-Json).accessToken | ConvertTo-SecureString -AsPlainText -Force
          Connect-MgGraph -AccessToken $accessToken
          # Install Maester
          Install-Module Maester -Force
          # Configure test results
          $PesterConfiguration = New-PesterConfiguration
          $PesterConfiguration.Output.Verbosity = 'None'
          # Run Maester tests
          $results = Invoke-Maester -Path tests/ -PesterConfiguration $PesterConfiguration -OutputFolder test-results -OutputFolderFileName "test-results" -PassThru
          # Add step summary
          $summary = Get-Content test-results/test-results.md
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $summary
          # Flag status to GitHub
          if ($results.Result -ne 'Passed'){
            Write-Error "Status = $($results.Result): See Maester Test Report below for details."
          }
        azPSVersion: "latest"

    - name: Archive Maester Html Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maester-test-results-${{ env.NOW }}
        path: test-results
```

Which is the same I was using before and same as published on website with the only exception I am running all tests and not just Maester ones.

So, after the execution these are the errors I am getting:

```
Run Maester TestsSystem.Management.Automation.RuntimeException: No test files were found and no scriptblocks were provided. Please ensure that you provided at least one path to a *.Tests.ps1 file, or a directory that contains such file. Or that you provided a ScriptBlock test container.

Run Maester TestsError: The process '/usr/bin/pwsh' failed with exit code 1

Run Maester TestsNo files were found with the provided path: test-results. No artifacts will be uploaded.

```
