### ISSUE TITLE
Unable to send email / 'not connected to Microsoft Graph'

### ISSUE THREAD

**Issue by riosengineer** [maester365/maester#316]
Hey all. Love the tool and thank you for the fantastic feature set!

I'm trying to send an email, as per the docs, but keep getting an error. I can't seem to figure out why - as I should be connected to Graph. My SPN has the correct email send API permissions. The default test run works fine, so graph is clearly ok. The below is a subsequent task to send an email out with the results.

Task (redacted info): 
```yaml
- task: AzurePowerShell@5
    displayName: "Email Maester"
    inputs:
      azureSubscription: "spn"
      pwsh: true
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        $userId = "xxxxx"
        $testResultsUri = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
        $results = Invoke-Maester -Path tests/Maester/ -PassThru
        Send-MtMail -MaesterResults $results -Recipient some@email.com -Subject 'Maester Results' -TestResultsUri $testResultsUri 
    condition: always()
```

Pipeline error: 

```
Exception: /home/vsts/.local/share/powershell/Modules/Maester/0.2.0/internal/Test-MtContext.ps1:40
Line |
  40 |          throw $message
     |          ~~~~~~~~~~~~~~
     | Not connected to Microsoft Graph. Please use 'Connect-Maester'. For more
     | information, use 'Get-Help Connect-Maester'.
##[error]PowerShell exited with code '1'.
```
If I use either any of these, I still get the message about not being connected:

```
Connect-Maester -Service All
or: 
$accessToken = (Get-AzAccessToken -ResourceTypeName MSGraph).Token | ConvertTo-SecureString -AsPlainText -Force
Connect-MgGraph -AccessToken $accessToken -Scopes (Get-MtGraphScope -SendMail)
```
Additionally, I am finding it difficult to understand via the docs how you pass the results to the results variable. I assume what I have above is correct but please if someone can assist to confirm that would be great too. 

Thanks

**Comment by Snozzberries** [comment]
Hi @riosengineer, thanks for reaching out. If you are connecting outside of the `Connect-Maester` command, you can use `Invoke-Maester -SkipGraphConnect`.

The Invoke command will be checking the module variable, which is set by the Connect command, so if you connect outside the module that variable is never set. You'll get other errors if you skip on invoke but still don't have the correct scopes.

I believe your command structure should work though.

**Comment by riosengineer** [comment]
> `Invoke-Maester -SkipGraphConnect`.

Thanks for the reply @Snozzberries! I've amended my email task to include the skip graph connect, like so, but no dice. It complains about a null name parameter from the `Invoke-MtGraphRequest` cmdlet:

ADO Task:

```
  - task: AzurePowerShell@5
    displayName: "Email Maester"
    inputs:
      azureSubscription: "wif-sc-maester"
      pwsh: true
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        $userId = "57f694c8-bc5f-4909-b882-10642ebd577c"
        $testResultsUri = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
        Invoke-Maester -SkipGraphConnect
        $results = Invoke-Maester -Path tests/Maester/ -PassThru 
        Send-MtMail -MaesterResults $results -Recipient dan@rios.engineer -Subject 'Maester Results' -TestResultsUri $testResultsUri 
    condition: always()
```

Pipeline error:

```
🔥 Skipping graph connection check
Invoke-MtGraphRequest: /home/vsts/.local/share/powershell/Modules/Maester/0.2.0/internal/ConvertTo-MtMaesterResults.ps1:15
Line |
  15 |          $org = Invoke-MtGraphRequest -RelativeUri 'organization'
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Name'. The argument is null or
     | empty. Provide an argument that is not null or empty, and then try the
     | command again.
##[error]PowerShell exited with code '1'.
```

Any ideas? Does anyone have a working ADO pipeline example I could refer to?

**Comment by Snozzberries** [comment]
Is your job running as an Entra service principal?

Like the below will not get you all the necessary scopes added to your token.

> $accessToken = (Get-AzAccessToken -ResourceTypeName MSGraph).Token | ConvertTo-SecureString -AsPlainText -Force
> Connect-MgGraph -AccessToken $accessToken -Scopes (Get-MtGraphScope -SendMail)

**Comment by riosengineer** [comment]
> Is your job running as an Entra service principal?
> 
> Like the below will not get you all the necessary scopes added to your token.
> 
> > $accessToken = (Get-AzAccessToken -ResourceTypeName MSGraph).Token | ConvertTo-SecureString -AsPlainText -Force
> > Connect-MgGraph -AccessToken $accessToken -Scopes (Get-MtGraphScope -SendMail)
> 
> CC @merill, not sure who authored the ADO docs.

Yes, federated identity, as per the docs. My 'Run Maester' task works fine, and publishes the results to view. Where I feel the docs are a bit more confusing to understand is the email & teams message section. For transparency, this is my entire pipeline (redacted info):

```
# Maester Daily Tests

trigger:
  - main

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzurePowerShell@5
    displayName: "Run Maester"
    inputs:
      azureSubscription: "SPN"
      pwsh: true
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        # Connect to Microsoft Graph
        $accessToken = (Get-AzAccessToken -ResourceTypeName MSGraph).Token | ConvertTo-SecureString -AsPlainText -Force
        Connect-MgGraph $accessToken

        # Install Maester
        Install-Module Maester -Force

        # Configure test results
        $PesterConfiguration = New-PesterConfiguration
        $PesterConfiguration.TestResult.Enabled = $true
        $PesterConfiguration.TestResult.OutputPath = '$(System.DefaultWorkingDirectory)/test-results/test-results.xml'

        # Run Maester tests
        Invoke-Maester -Path $(System.DefaultWorkingDirectory)/tests/Maester/ -PesterConfiguration $PesterConfiguration -OutputFolder '$(System.DefaultWorkingDirectory)/test-results'
  - publish: $(System.DefaultWorkingDirectory)/test-results
    displayName: Publish Maester Html Report
    artifact: TestResults

  - task: PublishTestResults@2
    displayName: Publish Pester Test Results
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "**/test-results.xml"
      failTaskOnFailedTests: true

  - task: AzurePowerShell@5
    displayName: "Email Maester"
    inputs:
      azureSubscription: "SPN"
      pwsh: true
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        $userId = "appRegGuid"
        $testResultsUri = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
        Invoke-Maester -SkipGraphConnect
        $results = Invoke-Maester -Path $(System.DefaultWorkingDirectory)/tests/Maester/ -PassThru 
        Send-MtMail -MaesterResults $results -Recipient example@email.com -Subject 'Maester Results' -TestResultsUri $testResultsUri 
    condition: always()
```

I followed the email docs from here: https://maester.dev/docs/monitoring/email

**Comment by merill** [comment]
Got it. So you don't need to create an additional task for mail, this is failing because you don't have a connect-mggraph in the "Email Maester" task.

Try this simpler version. 

The key changes are 
* Use -PassThru in Invoke-Maester and assign the results to $results
* Call Send-MtMail immediately after 
* Remove the entire "Email Maester" task block you have in your yml.

![Merill 2024-07-11 at 23 40 12@2x](https://github.com/maester365/maester/assets/1288081/c826ea22-9446-4bd0-8622-912367d8042b)

```
# Maester Daily Tests

trigger:
  - main

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzurePowerShell@5
    displayName: "Run Maester"
    inputs:
      azureSubscription: "SPN"
      pwsh: true
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        # Connect to Microsoft Graph
        $accessToken = (Get-AzAccessToken -ResourceTypeName MSGraph).Token | ConvertTo-SecureString -AsPlainText -Force
        Connect-MgGraph $accessToken

        # Install Maester
        Install-Module Maester -Force

        # Configure test results
        $PesterConfiguration = New-PesterConfiguration
        $PesterConfiguration.TestResult.Enabled = $true
        $PesterConfiguration.TestResult.OutputPath = '$(System.DefaultWorkingDirectory)/test-results/test-results.xml'

        # Run Maester tests
        $results = Invoke-Maester -Path $(System.DefaultWorkingDirectory)/tests/Maester/ -PesterConfiguration $PesterConfiguration -OutputFolder '$(System.DefaultWorkingDirectory)/test-results' -PassThru
 
		# Send Email
        $userId = "userObjectId"
        Send-MtMail -MaesterResults $results -Recipient example@email.com -UserId $UserId -Subject 'Maester Results' -TestResultsUri $testResultsUri 
```
