### ISSUE TITLE
GH: Errors after migrating from "inline script" to "marketplace Action"

### ISSUE THREAD

**Issue by Sar4D** [maester365/maester#483]
Hi, 
I am changing my Github action workflow from the inline script method to the marketplace action. 
However, when running it as showed in the docs, i get this error and i also get way more tests than before. 

![image](https://github.com/user-attachments/assets/35d9f563-5ae9-4dce-b015-47e59c909b91)

This is way I am using inside the workflow 

```

    - name: Invoke Measter action inside the repository
      uses: maester365/maester@main
      with:
        client_id: ${{ secrets.CLIENT_IDD }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        include_public_tests: false
        artifact_upload: true  
        step_summary: false
```

Any idea?
