### ISSUE TITLE
Running Github Action with only one include_tag set throws error about size of Markdown results

### ISSUE THREAD

**Issue by MattWhite-personal** [maester365/maester#607]
When running a Maester using the Github Action with a view to only run the Entra ID SCA tests the job runs but at the end of the run the upload fails with an error due to the size of the Markdown file 

Github Actions output snippet

```
WARNING: The version '5.6.1' of module 'Pester' is currently in use. Retry the operation after closing the applications.
Pester verbosity level set to: None
Running tests with tags: EIDSCA
███╗   ███╗ █████╗ ███████╗███████╗████████╗███████╗██████╗     ██╗   ██╗ ██╗    ██████╗
████╗ ████║██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔════╝██╔══██╗    ██║   ██║███║   ██╔═████╗
██╔████╔██║███████║█████╗  ███████╗   ██║   █████╗  ██████╔╝    ██║   ██║╚██║   ██║██╔██║
██║╚██╔╝██║██╔══██║██╔══╝  ╚════██║   ██║   ██╔══╝  ██╔══██╗    ╚██╗ ██╔╝ ██║   ████╔╝██║
██║ ╚═╝ ██║██║  ██║███████╗███████║   ██║   ███████╗██║  ██║     ╚████╔╝  ██║██╗╚██████╔╝
╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝      ╚═══╝   ╚═╝╚═╝ ╚═════╝
🔥 Maester test report generated at test-results/test-results.html
Tests Passed ✅: 63, Failed ❌: 15, Skipped ⚫: 9
Script execution Complete
Error: $GITHUB_STEP_SUMMARY upload aborted, supports content up to a size of 1024k, got 7872k. For more information see: https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions#adding-a-markdown-summary
```

I have recently switched from using the original v0.1 github action to the published one which has resulted in the error.

The code used in the Github Action yml is as follows

```yaml
name: Entra ID Secure Config Analyser

on:
  #push:
  #  branches: ["main"]
  # Run once a day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester action
      uses: maester365/maester@main
      with:
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        include_tags: "EIDSCA"
        include_public_tests: true
```

By comparison I have the original Maester tests using a separate action

```yaml
name: Maester Daily Tests

on:
  #push:
  #  branches: ["main"]
  # Run once a day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester action
      uses: maester365/maester@main
      with:
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        include_tags: "Maester"
        include_public_tests: false
```

The only changes being the `with` section has different `include_tags` and `include_public_tests` but changing the second from true to false doesn't resolve the issue just produce a smaller output file.

Looking at the contents of the Markdown that is published it is now much larger and is adding the Test Results summary multiple times at the end of the MD file (125 times when running `include_tags: EIDSCA` and `include_public_tests: true` and 52 tiles with `include_public_tests: false`). By comparison the logic for `include_tags: Maester` does not appear to produce the same errors

Reverting to the original GithubAction where all the code is run from the yml in my repo it completes without issue

```yaml
name: Entra ID Secure Config

on:
  #push:
  #  branches: ["main"]
  # Run once a day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%d-T%H%M%S')" >> $GITHUB_ENV
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
    - name: Run Maester
      uses: azure/powershell@v2
      with:
        inlineScript: |
          # Get Token
          $token = az account get-access-token --resource-type ms-graph

          # Connect to Microsoft Graph
          $accessToken = ($token | ConvertFrom-Json).accessToken | ConvertTo-SecureString -AsPlainText -Force
          Connect-MgGraph -AccessToken $accessToken

          # Install Maester
          Install-Module Maester -Force

          # Configure test results
          $PesterConfiguration = New-PesterConfiguration
          $PesterConfiguration.Output.Verbosity = 'None'

          # Run Maester tests
          $results = Invoke-Maester -Path tests/EIDSCA/ -PesterConfiguration $PesterConfiguration -OutputFolder test-results -OutputFolderFileName "test-results" -PassThru

          # Add step summary
          $summary = Get-Content test-results/test-results.md
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $summary

          # Flag status to GitHub - Uncomment the block below to fail the build if tests fail
          #if ($results.Result -ne 'Passed'){
          #  Write-Error "Status = $($results.Result): See Maester Test Report below for details."
          #}
        azPSVersion: "latest"

    - name: Archive Maester Html Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maester-test-results-${{ env.NOW }}
        path: test-results
```

I can't see why the logic should fail when the tests are being run from the public repo rather than locally and when EIDSCA is used as the tag
