### ISSUE TITLE
ORCA Tests all fail

### ISSUE THREAD

**Issue by Arcath** [maester365/maester#850]
We are using the GitHub action to run our tests and I've found that all the ORCA tests are failing with:

```
The term 'Test-ORCAXXX' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

**Comment by soulemike** [comment]
Do you have the prerelease version installed?

**Comment by Arcath** [comment]
We just use the GitHub action:

```yml
run-maester-tests:
    name: 🔥 Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester action
      uses: maester365/maester@main
      with:
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
```
