### ISSUE TITLE
🪲 Tests with missing tag

### ISSUE THREAD

**Issue by svrooij** [maester365/maester#985]
## Describe the bug

![Image](https://github.com/user-attachments/assets/5147726a-0036-4182-984c-d33b11bdc390)

Several tests have a badly formatted title, these should not be in the module like this:

- `Test-MtCaEnforceNonPersistentBrowserSession.Tests.ps1`
- `Test-MtCaMfaForGuest.Tests.ps1`

## To Reproduce

1. Execute `Invoke-Maester` `v1.1.16`
2. See the result

**Comment by merill** [comment]
I believe these are internal pester tests for testing the cmdlets and are in the ./powershell folder. These are only visible in dev.

The released module doesn't include these tests (we only include the ones in ./tests folder)

**Comment by svrooij** [comment]
@merill I used the new github actions, which calls install tests.

```ps1
  if ($IncludePublicTests -eq $true) {Add commentMore actions
        $publicTestsPath = Join-Path -Path $Path -ChildPath 'public-tests'
        Update-MtMaesterTests -Path $publicTestsPath -Force
    }
```

```yaml
    name: Maester 🔥
    runs-on: ubuntu-latest
    steps:
    - name: 🔥Run Maester 
      id: maester-action
      uses: maester365/maester-action@v1.0.1
      with:
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        include_public_tests: true # Optional: Set to false if you are keeping to a certain version of tests or have your own tests
        include_private_tests: false # no other tests yet
        include_exchange: false    # Optional: Set to true if you want to include Exchange tests
        include_teams: false # bla
        #include_tags: Maester,Security,Entra
        step_summary: true         # Optional: Set to false if you don't want a summary added to your GitHub Action run
        artifact_upload: true      # Optional: Set to false if you don't want summaries uploaded to GitHub Artifacts
        maester_version: preview  # Optional: Set to true if you want to use Measter Preview Build when running tests
        disable_telemetry: true   # Optional: Set to true If you want telemetry information not to be logged.
```
